### ISSUE TITLE
The installer should check the presence of Vagrant and VirtualBox 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-devinstaller#1]
If they are not present, the installer should fail fast.

**Comment by flbulgarelli** [comment]
@masch

**Comment by masch-zz** [comment]
I have created a PR adding validation for Git, Vagrant and VirtualBox programs.

**Comment by flbulgarelli** [comment]
Fixed by https://github.com/mumuki/mumuki-development-installer/pull/3
